/**
 * Help Content Constants
 *
 * All help text organized in sections for easy future i18n migration.
 * When localization system is implemented, move to:
 * /src/i18n/locales/en.ts under 'help.*' namespace
 * /src/i18n/locales/fi.ts for Finnish translations
 */

export const HELP_CONTENT = {
  // Page header
  PAGE_TITLE: 'Help & FAQ',
  BACK_TO_MENU: 'Back to Menu',

  // Section headers
  SECTION_GETTING_STARTED: 'Getting Started',
  SECTION_GENIE_DOLLARS: 'Genie Dollars System',
  SECTION_FEATURES: 'Features Overview',
  SECTION_TIPS: 'Tips & Shortcuts',
  SECTION_FAQ: 'Common Questions',

  // Getting Started
  GETTING_STARTED_DESC: 'Everything you need to know about ExamGenie',

  GETTING_STARTED_WHAT_IS: 'What is ExamGenie?',
  GETTING_STARTED_WHAT_IS_CONTENT: 'ExamGenie is an AI-powered study tool that helps you learn by transforming textbook images into interactive exams. Take exams, listen to audio summaries, and track your progress with our gamified reward system.',

  GETTING_STARTED_FIRST_EXAM: 'How to take your first exam',
  GETTING_STARTED_FIRST_EXAM_CONTENT: 'Upload textbook images from your mobile app → Select a grade level and category → ExamGenie generates 15 questions → Open the exam link on your computer or phone → Answer the questions → Submit and view your results instantly.',

  GETTING_STARTED_RESULTS: 'Understanding your results',
  GETTING_STARTED_RESULTS_CONTENT: 'Your results show your score, grade breakdown, and detailed feedback for each question. You can retake the exam after 12 hours, or practice just the questions you got wrong. Every attempt helps you improve!',

  // Genie Dollars System
  GENIE_DOLLARS_DESC: 'Earn rewards for studying',

  GENIE_DOLLARS_WHAT: 'What are Genie Dollars?',
  GENIE_DOLLARS_WHAT_CONTENT: 'Genie Dollars are virtual rewards you earn by completing study activities. They\'re displayed in the badge at the top of your exam menu. While they\'re just for fun right now, they encourage consistent learning habits and spaced repetition.',

  GENIE_DOLLARS_HOW_TO_EARN: 'How to earn Genie Dollars',
  GENIE_DOLLARS_HOW_TO_EARN_CONTENT: '📝 Take an exam: +10 Genie Dollars (first time only per 12 hours)\n🎧 Listen to audio summary: +5 Genie Dollars (must listen to 80% of duration)\n🔄 Retake an exam: +5 Genie Dollars (after 12 hours have passed)\n\nYou can only earn once per activity per 12-hour period. This encourages spaced repetition, a proven study technique.',

  GENIE_DOLLARS_COOLDOWN: 'Why the 12-hour cooldown?',
  GENIE_DOLLARS_COOLDOWN_CONTENT: 'The 12-hour waiting period between rewards is based on spaced repetition science. Returning to study material after a break helps you retain information better. It also prevents gaming the system by repeatedly taking the same exam.',

  GENIE_DOLLARS_AUDIO_REQUIREMENT: 'Why do I need to listen to 80% of the audio?',
  GENIE_DOLLARS_AUDIO_REQUIREMENT_CONTENT: 'We require 80% listening to ensure you actually benefit from the audio summary. Quick skipping to the end won\'t count. This threshold balances rewards with genuine learning.',

  // Features Overview
  FEATURES_DESC: 'What can you do in ExamGenie?',

  FEATURES_AUDIO: 'Audio Summary',
  FEATURES_AUDIO_CONTENT: 'Listen to an AI-generated overview of the exam material. The audio covers key concepts, important facts, and learning tips. Great for auditory learners or for preparing before taking the exam. Earn 5 Genie Dollars by listening to 80%+ of the audio.',

  FEATURES_TAKE_EXAM: 'Take Exam',
  FEATURES_TAKE_EXAM_CONTENT: 'Answer 15 multiple-choice questions generated by AI from your textbook images. Each question has 4 answer options. You can navigate between questions and review before submitting. Once submitted, your answers cannot be changed. Earn 10 Genie Dollars on completion.',

  FEATURES_VIEW_RESULTS: 'View Results',
  FEATURES_VIEW_RESULTS_CONTENT: 'See your score, grade, and detailed feedback for each question. Results display in "Story Mode" - swipe or tap to navigate through your performance card by card. You can also switch to "Legacy" view for a traditional list layout.',

  FEATURES_RETAKE_EXAM: 'Retake Full Exam',
  FEATURES_RETAKE_EXAM_CONTENT: 'Retake the entire exam after 12 hours to practice and improve. Your previous answer is shown in a bottom bar for reference. Unlimited retakes available. Earn 5 Genie Dollars each time.',

  FEATURES_PRACTICE_MISTAKES: 'Practice Mistakes',
  FEATURES_PRACTICE_MISTAKES_CONTENT: 'Practice only the questions you got wrong on your first attempt. See your previous incorrect answer for reference. Perfect for focused review and targeted improvement without repeating questions you already know.',

  // Tips & Shortcuts
  TIPS_DESC: 'Pro tips for better learning',

  TIPS_AUDIO_FIRST: 'Listen to audio before taking the exam',
  TIPS_AUDIO_FIRST_CONTENT: 'The audio summary gives you key concepts and context. Starting with audio helps you understand the material better and perform better on the exam.',

  TIPS_PRACTICE_MISTAKES: 'Use Practice Mistakes for focused review',
  TIPS_PRACTICE_MISTAKES_CONTENT: 'After your first attempt, use the Practice Mistakes feature to drill weak areas. This targeted approach is more efficient than retaking the whole exam.',

  TIPS_STORY_MODE_NAV: 'Story Mode navigation shortcuts',
  TIPS_STORY_MODE_NAV_CONTENT: '← / → : Navigate between result cards\nSpace : Next card\nEsc : Exit\nTap left/right 30% of screen : Next/Previous\nSwipe left/right : Navigate (mobile)',

  TIPS_SPACED_REPETITION: 'Use spaced repetition for better retention',
  TIPS_SPACED_REPETITION_CONTENT: 'The 12-hour cooldown between rewards is intentional! Returning to study material after a break (spaced repetition) helps you retain information much longer than cramming.',

  // FAQ
  FAQ_DESC: 'Answers to common questions',

  FAQ_NO_REWARD: 'Why didn\'t I earn Genie Dollars?',
  FAQ_NO_REWARD_CONTENT: 'Common reasons:\n• 12-hour cooldown hasn\'t passed since your last attempt\n• For audio: You didn\'t listen to at least 80% of the duration\n• The activity counter resets every 12 hours\nCheck the badge status - it shows how many hours until the next reward is available.',

  FAQ_RETAKE_VS_PRACTICE: 'What\'s the difference between Retake and Practice Mistakes?',
  FAQ_RETAKE_VS_PRACTICE_CONTENT: '• Retake Full Exam: Answer all 15 questions again. Great for overall review and practice.\n• Practice Mistakes: Only answer the questions you got wrong. Great for focused improvement.\n\nBoth count toward your Genie Dollars rewards (if 12 hours have passed).',

  FAQ_GRADING: 'How is my exam graded?',
  FAQ_GRADING_CONTENT: 'ExamGenie uses AI-powered grading to evaluate your answers and provide detailed feedback. Each question receives a score (correct, partial, or incorrect) based on your answer. Your final grade is calculated from the total points earned.',

  FAQ_PARTIAL_CREDIT: 'Why did I get partial credit?',
  FAQ_PARTIAL_CREDIT_CONTENT: 'Some questions may have multiple valid interpretations or partially correct answers. The AI grader awards partial credit when your answer shows understanding but isn\'t completely correct or complete.',

  FAQ_RESULTS_COLORS: 'What do the colors in Story Mode results mean?',
  FAQ_RESULTS_COLORS_CONTENT: '🟢 Green: Correct answer\n🟠 Orange: Partial credit\n🔴 Red: Incorrect answer\n\nEach card shows your answer, the correct answer, and feedback explaining the question.',

  FAQ_RETAKE_AFTER_HOURS: 'Can I retake before 12 hours?',
  FAQ_RETAKE_AFTER_HOURS_CONTENT: 'Yes! You can retake the exam anytime. However, you\'ll only earn Genie Dollars for the retake if at least 12 hours have passed since your last reward for that activity. You can still practice and review without earning rewards.',

  FAQ_QUESTIONS_SAME: 'Are the questions the same every time?',
  FAQ_QUESTIONS_SAME_CONTENT: 'Yes, the 15 questions stay the same for each exam. This consistency helps you track your improvement when you retake the exam. Answer order may vary due to our answer shuffling algorithm.',

  FAQ_LEADERBOARD: 'When is the Leaderboard coming?',
  FAQ_LEADERBOARD_CONTENT: 'The Leaderboard feature is coming soon! It will let you compare your scores with friends and classmates to add a friendly competitive element to studying.',
} as const
