-- Migration: Add audio summary support to examgenie_exams table
-- Purpose: Store generated summary text, audio URL, and audio metadata
-- Date: 2025-10-13

-- Add columns for audio summary feature
ALTER TABLE examgenie_exams
  ADD COLUMN summary_text TEXT,
  ADD COLUMN audio_url TEXT,
  ADD COLUMN audio_metadata JSONB;

-- Add index for audio_url lookups (for monitoring which exams have audio)
CREATE INDEX idx_examgenie_exams_audio_url ON examgenie_exams(audio_url);

-- Add comment explaining the columns
COMMENT ON COLUMN examgenie_exams.summary_text IS 'Educational summary text (~1000 words) generated by Gemini alongside exam questions';
COMMENT ON COLUMN examgenie_exams.audio_url IS 'Public URL to MP3 audio file in Supabase Storage (audio-summaries bucket)';
COMMENT ON COLUMN examgenie_exams.audio_metadata IS 'TTS generation metadata: voice config, duration, file size, generation timestamp';
